export const DEFAULT_PROMPTS = {
    questions: JSON.stringify({
        system: "You are an expert product manager and technical architect.",
        prompt: "I have a project idea: \"${idea}\"\n\nGenerate 3-5 thoughtful, specific questions that would help refine this idea and uncover important requirements, technical considerations, and feature needs. \n\nReturn ONLY a JSON array of strings (the questions), nothing else. Format: [\"question 1\", \"question 2\", ...]"
    }),
    blueprint: JSON.stringify({
        system: "You are an expert software architect and product strategist.",
        prompt: "Based on this project idea and answers, create a comprehensive technical blueprint in markdown format.\n\nPROJECT IDEA: \"${idea}\"\n\nCLARIFYING Q&A:\n${qaPairs}\n\nCRITICAL TECH STACK GUIDELINES:\n- Recommend MODERN, SIMPLE solutions that get users up and running quickly\n- Prefer: Next.js, Vite + React, Supabase, Resend, n8n, Tailwind CSS, shadcn/ui\n- Avoid over-engineering - choose the simplest viable approach\n- Focus on aesthetic, eye-catching design with minimal complexity\n- This is for \"vibe-coders\" and non-traditional developers\n\nGenerate a complete markdown blueprint with these sections:\n# Project Blueprint: [Project Name]\n\n## Overview\nBrief description and purpose\n\n## Core Features\nComprehensive list of all necessary features\n\n## Recommended Tech Stack\nModern, simple technologies optimized for rapid development\n\n## Architecture\nHigh-level system architecture (keep simple)\n\n## Data Models\nKey entities and relationships\n\n## User Flow\nPrimary user journeys\n\n## Implementation Phases\nSuggested development phases\n\n## Design Principles\nAesthetic and UX considerations\n\n## Considerations\nTechnical constraints, security, performance, scalability\n\n---\n\n## Master Takeoff Prompt\n\n[Generate a comprehensive, ready-to-use prompt that can be pasted directly into Cursor, Lovable, Bolt, Replit, or similar AI coding tools. This should include:\n- Complete project context\n- Tech stack specifications\n- Core features to implement\n- Design requirements\n- File structure suggestions\n- Any specific implementation details\nMake it detailed enough that an AI agent can start building immediately.]\n\nBe specific, thorough, and technical. This should serve as a complete development blueprint."
    }),
    refine: JSON.stringify({
        system: "You are helping refine a project blueprint for \"vibe-coders\" and non-traditional developers. The user may ask for changes, additions, clarifications, or complete rewrites. \n\nALWAYS respond with the updated COMPLETE blueprint in markdown format, incorporating their feedback.\n\nCRITICAL TECH STACK PRINCIPLES:\n- Recommend MODERN, SIMPLE solutions (Next.js, Vite + React, Supabase, Resend, n8n, Tailwind, shadcn/ui)\n- Avoid over-engineering - simplest viable approach wins\n- Focus on aesthetic, eye-catching design\n- Optimize for rapid development and deployment\n\nThe blueprint must end with a \"## Master Takeoff Prompt\" section that's ready to paste into Cursor, Lovable, Bolt, or Replit. Be thorough and technical."
    }),
    mockup: JSON.stringify({
        system: "You are an expert UI/UX designer and frontend developer specializing in data visualization and app showcases.",
        prompt: "Based on this project blueprint, create a complete, standalone HTML file that VISUALIZES the concept.\n\nBLUEPRINT:\n${blueprint}\n\nAnalyze the blueprint to determine if this is primarily a \"User Interface (App/Website)\" or a \"Process/Workflow\".\n\nIF IT IS AN APP OR WEBSITE:\n- Create a visual mockup of the interface displayed with a \"Perspective Design\" style.\n- Frame the main interface in a stylized window or device container that has a subtle 3D tilt/perspective effect (using CSS transform: perspective/rotate3d) to make it look like a high-end showcase.\n- The design should look like it's \"floating\" in 3D space.\n- Ensure the UI itself is within this transformed container.\n- It should look \"premium\" and modern, verifying the \"vibe\" of the idea.\n\nIF IT IS A WORKFLOW, SYSTEM, OR AUTOMATION:\n- Create a \"Line Tree Diagram\" or flowchart visualization.\n- Use SVGs or CSS to draw nodes and connecting lines representing the steps/logic of the workflow.\n- Make it interactive (hover effects on nodes.\n- It should clearly visualize the logic flow, branching, and outputs.\n\nGENERAL REQUIREMENTS:\n- Single HTML file with embedded CSS and JavaScript.\n- Beautiful, MODERN, eye-catching design.\n- Showcase 3-5 signature features.\n- Include the project goal/mission.\n- Focus on SIMPLICITY and AESTHETICS.\n- Use Google Fonts.\n- Dark mode preference unless otherwise specified.\n- Clean, minimal code.\n\nIMPORTANT: At the bottom of the HTML, include a hidden section with the full markdown blueprint embedded in a <pre> tag with id=\"markdown-content\". Add a \"Copy Blueprint\" button that copies this markdown to clipboard. Style it minimally.\n\nReturn ONLY the complete HTML code, nothing else."
    })
};
